name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: MaxPizzaBoy/github-pages-overwriter@v3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
          keep_files: false # Set to true if you want to keep existing files
          directory: www # Specify the folder you want to deploy
